doctrine:
  
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:

      User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/User/Adapter/Database/Orm/Doctrine/Mapping'
        prefix: 'User\Domain\Model'
        alias: User

      Profile:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/User/Adapter/Database/Orm/Doctrine/Mapping'
        prefix: 'User\Domain\Model'
        alias: User