User:
  resource: "../../../../../User/Adapter/Framework/Config/routes/routes.yaml"

Group:
  resource: "../../../../../Group/Adapter/Framework/Config/routes/routes.yaml"

Notification:
  resource: "../../../../../Notification/Adapter/Framework/Config/routes/routes.yaml"
