doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Product:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Product/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Product\Domain\Model'
                alias: Product

            ProductsShops:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Product/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Product\Domain\Model'
                alias: ProductShop
