services:
  _defaults:
    autowire: true
    autoconfigure: true

    bind:
      $systemKey: "%system.key%"

  # Adapter
  Notification\Adapter\:
    resource: "../../../../../Notification/Adapter/"

  # Application
  Notification\Application\:
    resource: "../../../../../Notification/Application/"

  # Domain
  Notification\Domain\:
    resource: "../../../../../Notification/Domain/"
