# -------------------------------------------------------------
# LIST ORDERS CREATE
list_orders_create:
  path: /api/v{api_version}/list-orders
  methods: POST
  controller: ListOrders\Adapter\Http\Controller\ListOrdersCreate\ListOrdersCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS MODIFY
# -------------------------------------------------------------
list_orders_modify:
  path: /api/v{api_version}/list-orders
  methods: PUT
  controller: ListOrders\Adapter\Http\Controller\ListOrdersModify\ListOrdersModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS GET DATA
# -------------------------------------------------------------
list_orders_get_data:
  path: /api/v{api_version}/list-orders
  methods: GET
  controller: ListOrders\Adapter\Http\Controller\ListOrdersGetData\ListOrdersGetDataController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS REMOVE
# -------------------------------------------------------------
list_orders_remove:
  path: /api/v{api_version}/list-orders
  methods: DELETE
  controller: ListOrders\Adapter\Http\Controller\ListOrdersRemove\ListOrdersRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS ADD ORDERS
# -------------------------------------------------------------
list_orders_add_orders:
  path: /api/v{api_version}/list-orders/order
  methods: POST
  controller: ListOrders\Adapter\Http\Controller\ListOrdersAddOrder\ListOrdersAddOrderController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS GET ORDERS
# -------------------------------------------------------------
list_orders_get_orders:
  path: /api/v{api_version}/list-orders/order
  methods: GET
  controller: ListOrders\Adapter\Http\Controller\ListOrdersGetOrders\ListOrdersGetOrdersController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS REMOVE ORDERS
# -------------------------------------------------------------
list_orders_remove_orders:
  path: /api/v{api_version}/list-orders/order
  methods: DELETE
  controller: ListOrders\Adapter\Http\Controller\ListOrdersRemoveOrder\ListOrdersRemoveOrderController
  requirements:
    api_version: '\d+[.\d]?'
