# -------------------------------------------------------------
# LIST ORDERS CREATE
list_orders_create:
  path: /api/v{api_version}/list-orders
  methods: POST
  controller: ListOrders\Adapter\Http\Controller\ListOrdersCreate\ListOrdersCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS MODIFY
# -------------------------------------------------------------
list_orders_modify:
  path: /api/v{api_version}/list-orders
  methods: PUT
  controller: ListOrders\Adapter\Http\Controller\ListOrdersModify\ListOrdersModifyController
  requirements:
    api_version: '\d+[.\d]?'
