doctrine:
    orm:
        enable_lazy_ghost_objects: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Group:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Group/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Group\Domain\Model'

            UserGroup:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Group/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Group\Domain\Model'
