doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        types:
            IdentifierType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\IdentifierType
            EmailType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\EmailType
            PasswordType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\PasswordType
            NameType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\NameType
            DescriptionType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\DescriptionType
            PathType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\PathType
            LanguageType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\LanguageType
            UrlType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\UrlType
            RolesType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\Array\RolesType
            GroupTypeType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\GroupTypeType
            NotificationTypeType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\String\NotificationTypeType
            NotificationDataType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\Array\NotificationDataType
            AmountType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\Float\AmountType
            MoneyType: Common\Adapter\Database\Orm\Doctrine\Mapping\Type\Float\MoneyType

    orm:
        dql:
            string_functions:
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

        # IMPORTANT: You MUST configure your server version,
        # either    here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

imports:
    - {
          resource: "../../../../../Group/Adapter/Framework/Config/packages/doctrine.yaml",
      }
    - {
          resource: "../../../../../Order/Adapter/Framework/Config/packages/doctrine.yaml",
      }
    - {
          resource: "../../../../../Product/Adapter/Framework/Config/packages/doctrine.yaml",
      }
    - {
          resource: "../../../../../Shop/Adapter/Framework/Config/packages/doctrine.yaml",
      }
    - {
          resource: "../../../../../User/Adapter/Framework/Config/packages/doctrine.yaml",
      }
    - {
          resource: "../../../../../Notification/Adapter/Framework/Config/packages/doctrine.yaml",
      }
