framework:
    default_locale: en
    translator:
        default_path: "%kernel.project_dir%/src/Common/Domain/Translation"
        fallbacks:
            - en
        paths:
            - "%kernel.project_dir%/src/User/Domain/Translation"
