# -------------------------------------------------------------
# ORDER CREATE
order_create:
  path: /api/v{api_version}/orders
  methods: POST
  controller: Order\Adapter\Http\Controller\OrderCreate\OrderCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# ORDER MODIFY
# -------------------------------------------------------------
order_modify:
  path: /api/v{api_version}/orders
  methods: PUT
  controller: Order\Adapter\Http\Controller\OrderModify\OrderModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# ORDER REMOVE
# -------------------------------------------------------------
order_remove:
  path: /api/v{api_version}/orders
  methods: DELETE
  controller: Order\Adapter\Http\Controller\OrderRemove\OrderRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# ORDER GET DATA
# -------------------------------------------------------------
order_get_data:
  path: /api/v{api_version}/orders
  methods: GET
  controller: Order\Adapter\Http\Controller\OrderGetData\OrderGetDataController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# ORDER SET BOUGHT
# -------------------------------------------------------------
orders_bought:
  path: /api/v{api_version}/orders/bought
  methods: PATCH
  controller: Order\Adapter\Http\Controller\OrderBought\OrderBoughtController
  requirements:
    api_version: '\d+[.\d]?'
