doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ListOrders:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Order/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Order\Domain\Model'
                alias: ListOrders

            ListOrdersOrders:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Order/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Order\Domain\Model'
                alias: ListOrdersOrders

            Order:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Order/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Order\Domain\Model'
                alias: Order
