user_register:
    path: /api/v{api_version}/{_locale}/user/register
    methods: POST
    controller: User\Adapter\Http\Controller\UserRegister\UserRegisterController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es

user_email_confirmation:
    path: /api/v{api_version}/{_locale}/user/email/confirmation/{token}
    methods: GET
    controller: User\Adapter\Http\Controller\UserEmailConfirmation\UserEmailConfirmationController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es

user_remember_password:
    path: /api/v{api_version}/{_locale}/user/password/remember
    methods: PATCH
    controller: User\Adapter\Http\Controller\UserPasswordRemember\UserPasswordRememberController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es

user_password_remember_confirm:
    path: /api/v{api_version}/{_locale}/user/password/remember/confirm
    methods: PATCH
    controller: User\Adapter\Http\Controller\UserPasswordRemember\UserPasswordRememberController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es
