# -------------------------------------------------------------
# USER REGISTRATION
user_register:
  path: /api/v{api_version}/users
  methods: POST
  controller: User\Adapter\Http\Controller\UserRegister\UserRegisterController
  requirements:
    api_version: '\d+[.\d]?'

user_email_confirmation:
  path: /api/v{api_version}/users/confirm
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserRegisterEmailConfirmation\UserRegisterEmailConfirmationController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER PASSWORD REMEMBER
# -------------------------------------------------------------
user_password_remember:
  path: /api/v{api_version}/users/remember
  methods: POST
  controller: User\Adapter\Http\Controller\UserPasswordRemember\UserPasswordRememberController
  requirements:
    api_version: '\d+[.\d]?'

user_password_remember_change:
  path: /api/v{api_version}/users/password-remember
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserPasswordRememberChange\UserPasswordRememberChangeController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER PASSWORD CHANGE
# -------------------------------------------------------------
user_password_change:
  path: /api/v{api_version}/users/password
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserPasswordChange\UserPasswordChangeController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER EMAIL CHANGE
# -------------------------------------------------------------
user_email_change:
  path: /api/v{api_version}/users/email
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserEmailChange\UserEmailChangeController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER LOGIN
# -------------------------------------------------------------
user_login:
  path: /api/v{api_version}/users/login
  methods: POST
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER REMOVE
# -------------------------------------------------------------
user_delete:
  path: /api/v{api_version}/users/remove/{id}
  methods: DELETE
  controller: User\Adapter\Http\Controller\UserRemove\UserRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GET USERS BY ID
# -------------------------------------------------------------
user_get:
  path: /api/v{api_version}/users/{users_id}
  methods: GET
  controller: User\Adapter\Http\Controller\GetUsers\GetUsersController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GET USERS BY NAME
# -------------------------------------------------------------
user_get_by_name:
  path: /api/v{api_version}/users/name/{users_name}
  methods: GET
  controller: User\Adapter\Http\Controller\UserGetByName\UserGetByNameController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PROFILE
# -------------------------------------------------------------
user_modify:
  path: /api/v{api_version}/users/modify
  methods: [PUT, POST]
  controller: User\Adapter\Http\Controller\UserModify\UserModifyController
  requirements:
    api_version: '\d+[.\d]?'
