# -------------------------------------------------------------
# USER REGISTRATION
user_register:
  path: /api/v{api_version}/users
  methods: POST
  controller: User\Adapter\Http\Controller\UserRegister\UserRegisterController
  requirements:
    api_version: '\d+[.\d]?'

user_email_confirmation:
  path: /api/v{api_version}/users/confirm/{token}
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserEmailConfirmation\UserEmailConfirmationController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER PASSWORD REMEMBER
# -------------------------------------------------------------
user_password_rememeber:
  path: /api/v{api_version}/users/remember
  methods: POST
  controller: User\Adapter\Http\Controller\UserPasswordRemember\UserPasswordRememberController
  requirements:
    api_version: '\d+[.\d]?'
    _locale: en|es

user_password_remember_change:
  path: /api/v{api_version}/users/password-remember
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserPasswordRememberChange\UserPasswordRememberChangeController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# USER PASSWORD CHANGE
# -------------------------------------------------------------
user_password_change:
  path: /api/v{api_version}/users/password
  methods: PATCH
  controller: User\Adapter\Http\Controller\UserPasswordChange\UserPasswordChangeController
  requirements:
    api_version: '\d+[.\d]?'
    _locale: en|es

# -------------------------------------------------------------
# USER LOGIN
# -------------------------------------------------------------
user_login:
  # path: /api/v{api_version}/{_locale}/user/login
  path: /api/v{api_version}/users/login
  methods: POST
  requirements:
    api_version: '\d+[.\d]?'
