user_register:
    path: /api/v{api_version}/{_locale}/user/register
    methods: POST
    controller: User\Adapter\Http\Controller\UserRegister\UserRegisterController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es

user_email_confirmation:
    path: /api/v{api_version}/{_locale}/user/email/confirmation/{token}
    methods: GET
    controller: User\Adapter\Http\Controller\UserEmailConfirmation\UserEmailConfirmationController
    requirements:
        api_version: '\d+[.\d]?'
        _locale: en|es
