create:
    path: /create
    controller: User\Application\Create\UserCreate
    methods: POST

update:
    path: /update/{id}
    controller: User\Application\Update\UserUpdateAction
    methods: PUT    