imports:
    - {
          resource: "../../../../../User/Adapter/Framework/Config/services/services.yaml",
      }
    - {
          resource: "../../../../../Group/Adapter/Framework/Config/services/services.yaml",
      }
    - {
          resource: "../../../../../Notification/Adapter/Framework/Config/services/services.yaml",
      }
parameters:
    common.environment.app_env: "%env(string:APP_ENV)%"
    common.app_name: "%env(string:APP_NAME)%"
    common.system.key: "%env(string:SYSTEM_KEY)%"
    user.jwt_key: "%env(file:resolve:JWT_SECRET_KEY)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $appEnv: "%common.environment.app_env%"

    # Adapter
    Common\Adapter\:
        resource: "../../../../Adapter/"
        exclude: "../../../../Adapter/Framework/"

    # Domain
    Common\Domain\:
        resource: "../../../../Domain/"

    Common\Adapter\Jwt\JwtLexikAdapter:
        arguments:
            $secretKey: "%user.jwt_key%"

    Common\Adapter\Http\ArgumentResolver\ArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    Test\Fixtures\Helpers\AliceBundleHelpers: ~
