imports:
    - { resource: '../../../../../User/Adapter/Framework/Config/services/services.yaml' }    

services:

    _defaults:
        autowire: true    
        autoconfigure: true 


    Common\Adapter\Http\ArgumentResolver\ArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    # Services
    Common\Adapter\:
        resource: '../../../'
        exclude: '../../../Framework/'

    Common\Domain\:
        resource: '../../../../Domain/'

    
