imports:
    - {
          resource: "../../../../../User/Adapter/Framework/Config/services/services.yaml",
      }
parameters:
    common.enviroment.app_env: "%env(string:APP_ENV)%"
    common.app_name: "%env(string:APP_NAME)%"
    common.admin_email: "%env(string:ADMIN_EMAIL)%"
    common.user_register_key: "%env(string:USER_REGISTER_KEY)%"
    common.email_user_registration_confirmation_expire: "%env(int:EMAIL_REGISTRATION_CONFIRM_EXPIRE)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $appEnv: "%common.enviroment.app_env%"

    # Adapter
    Common\Adapter\:
        resource: "../../../../Adapter/"
        exclude: "../../../../Adapter/Framework/"

    # Domain
    Common\Domain\:
        resource: "../../../../Domain/"

    Common\Adapter\Jwt\JwtFirebaseHS256Adapter:
        arguments:
            $secretKey: "%env(file:resolve:JWT_KEY_FILE)%"

    Common\Adapter\Http\ArgumentResolver\ArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
