services:
  _defaults:
    autowire: true
    autoconfigure: true

    bind:

  # Adapter
  Order\Adapter\:
    resource: "../../../../../Order/Adapter/"

  # Application
  Order\Application\:
    resource: "../../../../../Order/Application/"

  # Domain
  Order\Domain\:
    resource: "../../../../../Order/Domain/"
