parameters:
    user.image.path: "%env(string:USER_IMAGE_PATH)%"
    user.public.image.path: "%env(string:USER_IMAGE_PUBLIC_PATH)%"
    user.email_user_registration_confirmation_expire: "%env(int:EMAIL_REGISTRATION_CONFIRM_EXPIRE)%"
    user.email_user_password_remember_expire: "%env(int:EMAIL_PASSWORD_REMEMBER_EXPIRE)%"
    user.admin_email: "%env(string:ADMIN_EMAIL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appName: "%common.app_name%"
            $adminEmail: "%user.admin_email%"
            $appProtocolAndDomain: "%common.app.protocolAndDomain%"
            $emailUserRegistrationConfirmationExpire: "%user.email_user_registration_confirmation_expire%"
            $emailUserPasswordRememberExpire: "%user.email_user_password_remember_expire%"
            $userImagePath: "%user.image.path%"
            $userPublicImagePath: "%user.public.image.path%"
            $systemKey: "%common.system.key%"
            $userActivationTimeExpiration: "%user.email_user_registration_confirmation_expire%"

    # Adapter
    User\Adapter\:
        resource: "../../../../../User/Adapter/"

    # Application
    User\Application\:
        resource: "../../../../../User/Application/"

    # Domain
    User\Domain\:
        resource: "../../../../../User/Domain/"

    # Event subscriber loader
    Common\Domain\Ports\Event\EventDispatcherInterface $eventDispatcherSubscriberLoader: '@Common\Adapter\Compiler\RegisterEventDomain\EventSubscriberLoader'
    Common\Domain\Ports\Event\EventDispatcherInterface: '@Common\Adapter\Event\EventDispatcherSymfonyAdapter'
