services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Adapter
    User\Adapter\:
        resource: "../../../../../User/Adapter/"

    # Application
    User\Application\:
        resource: "../../../../../User/Application/"

    # Domain
    User\Domain\:
        resource: "../../../../../User/Domain/"

    User\Domain\Service\UserRegisterKeyValidation\UserRegisterKeyValidationService:
        arguments:
            $registerKey: "%env(string:USER_REGISTER_KEY)%"
