parameters:
    user.image.path: "%env(string:USER_IMAGE_PATH)%"
    user.public.image.path: "%env(string:USER_IMAGE_PUBLIC_PATH)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appName: "%common.app_name%"
            $adminEmail: "%common.admin_email%"
            $emailUserRegistrationConfirmationExpire: "%common.email_user_registration_confirmation_expire%"
            $emailUserPasswordRememberExpire: "%common.email_user_password_remember_expire%"
            $userImagePath: "%user.image.path%"
            $userPublicImagePath: "%user.public.image.path%"
            $systemKey: "%common.system.key%"

    # Adapter
    User\Adapter\:
        resource: "../../../../../User/Adapter/"

    # Application
    User\Application\:
        resource: "../../../../../User/Application/"

    # Domain
    User\Domain\:
        resource: "../../../../../User/Domain/"

    # Event subscriber loader
    Common\Domain\Ports\Event\EventDispatcherInterface $eventDispatcherSubscriberLoader: '@Common\Adapter\Compiler\RegisterEventDomain\EventSubscriberLoader'
    Common\Domain\Ports\Event\EventDispatcherInterface: '@Common\Adapter\Event\EventDispatcherSymfonyAdapter'
