services:

    _defaults:
        autowire: true    
        autoconfigure: true 


    # Controllers
    User\Adapter\:
        resource: '../../../'
        exclude: '../../../Framework/'

    # Services
    User\Domain\:
        resource: '../../../../Domain/'
    
    User\Application\:
        resource: '../../../../Application/'

    User\Adapter\Database\Orm\Doctrine\Repository\UserRepository: ~
    User\Domain\Repository\Port\UserRepositoryInterface: '@User\Adapter\Database\Orm\Doctrine\Repository\UserRepository'
