services:

    _defaults:
        autowire: true    
        autoconfigure: true 


    # Controllers
    User\Adapter\:
        resource: '../../../'
        exclude: '../../../Framework/'

    # Services
    User\Domain\:
        resource: '../../../../Domain/'

    User\Domain\Service\UserRegisterKeyValidationService:
        arguments: ['%env(string:USER_REGISTER_KEY)%']
    
    User\Application\:
        resource: '../../../../Application/'

    User\Adapter\Database\Orm\Doctrine\Repository\UserRepository: ~
    User\Domain\Port\Repository\UserRepositoryInterface: '@User\Adapter\Database\Orm\Doctrine\Repository\UserRepository'
