services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # User\:
    #     resource: '%kernel.project_dir%/User/Domain/Service/'

    # User\Adapter\Controller\:
    #     resource: '%kernel.project_dir%/User/Adapter/Http/Controller/UserCreate'
    #     tags: ['controller.service_arguments']