services:

    _defaults:
        autowire: true    
        autoconfigure: true 


    # Controllers
    User\Adapter\Controller\:
        resource: '../../../Controller/'

    # Services
    User\Domain\Service\:
        resource: '../../../../Domain/Service/'

    # Models
    User\Domain\Model\:
        resource: '../../../../Domain/Model/'

    User\Adapter\Database\Orm\Doctrine\Repository\UserRepository: ~
    User\Domain\Repository\IUserRepository: '@User\Adapter\Database\Orm\Doctrine\Repository\UserRepository'
