services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    User\Adapter\Controller\:
        resource: '../../../../../User/Adapter/Controller/'
        # tags: ['controller.service_arguments']