# -------------------------------------------------------------
# NOTIFICATION REMOVE
notification_create:
  path: /api/v{api_version}/notification
  methods: POST
  controller: Notification\Adapter\Http\Controller\NotificationCreate\NotificationCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# NOTIFICATION REMOVE
# -------------------------------------------------------------
notification_remove:
  path: /api/v{api_version}/notification
  methods: DELETE
  controller: Notification\Adapter\Http\Controller\NotificationRemove\NotificationRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# NOTIFICATION GET DATA
# -------------------------------------------------------------
notification_get_data:
  path: /api/v{api_version}/notification
  methods: GET
  controller: Notification\Adapter\Http\Controller\NotificationGetData\NotificationGetDataController
  requirements:
    api_version: '\d+[.\d]?'
