--- # -------------------------------------------------------------
# -------------------------------------------------------------
# GROUP REMOVE
notification_create:
  path: /api/v{api_version}/notification
  methods: POST
  controller: Notification\Adapter\Http\Controller\NotificationCreate\NotificationCreateController
  requirements:
    api_version: '\d+[.\d]?'
