# -------------------------------------------------------------
# GROUP CREATE
group_create:
  path: /api/v{api_version}/groups
  methods: POST
  controller: Group\Adapter\Http\Controller\GroupCreate\GroupCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP REMOVE
# -------------------------------------------------------------
group_remove:
  path: /api/v{api_version}/groups
  methods: DELETE
  controller: Group\Adapter\Http\Controller\GroupRemove\GroupRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP MODIFY
# -------------------------------------------------------------
group_modify:
  path: /api/v{api_version}/groups/modify
  methods: PUT
  controller: Group\Adapter\Http\Controller\GroupModify\GroupModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP USER GET GROUPS
# -------------------------------------------------------------
group_user_get_groups:
  path: /api/v{api_version}/groups/user-groups
  methods: GET
  controller: Group\Adapter\Http\Controller\GroupUserGetGroups\GroupUserGetGroupsController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP USER GET GROUPS
# -------------------------------------------------------------
group_group_get_users:
  path: /api/v{api_version}/groups/user/{group_id}
  methods: GET
  controller: Group\Adapter\Http\Controller\GroupGetUsers\GroupGetUsersController
  requirements:
    api_version: '\d+[.\d]?'
    groups_id: "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"

# -------------------------------------------------------------
# GROUP USER GET GROUPS
# -------------------------------------------------------------
group_get_admins:
  path: /api/v{api_version}/groups/admins/{group_id}
  methods: GET
  controller: Group\Adapter\Http\Controller\GroupGetAdmins\GroupGetAdminsController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP GET DATA
# -------------------------------------------------------------
group_get_data:
  path: /api/v{api_version}/groups/data/{groups_id}
  methods: GET
  controller: Group\Adapter\Http\Controller\GroupGetData\GroupGetDataController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP USER ADD
# -------------------------------------------------------------
group_user_add:
  path: /api/v{api_version}/groups/user
  methods: POST
  controller: Group\Adapter\Http\Controller\GroupUserAdd\GroupUserAddController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP USER REMOVE
# -------------------------------------------------------------
group_user_remove:
  path: /api/v{api_version}/groups/user
  methods: DELETE
  controller: Group\Adapter\Http\Controller\GroupUserRemove\GroupUserRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# GROUP CHANGE USER ROLE
# -------------------------------------------------------------
group_user_role_change:
  path: /api/v{api_version}/groups/user/role
  methods: PUT
  controller: Group\Adapter\Http\Controller\GroupUserRoleChange\GroupUserRoleChangeController
  requirements:
    api_version: '\d+[.\d]?'
